// Template catalog with dummy data and styling for previews and builder
export const TEMPLATES = [
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    description: 'Single-column, clean spacing, uppercase headings',
    layout: { type: 'single-column' },
    theme: {
      fontFamily: "'Inter', Arial, sans-serif",
      nameSize: '32px',
      jobSize: '15px',
      bodySize: '11px',
      sectionSize: '14px',
      weightBold: 700,
      weightBody: 400,
      primary: '#111',
      secondary: '#444',
      accent: '#000',
      background: '#fff',
      divider: '#000',
      contactSeparator: ' | ',
      bullet: '•',
      sectionSpacing: '18px',
      itemSpacing: '10px',
      padding: '32px 40px',
    },
    sections: ['contact', 'summary', 'education', 'workExperience', 'skills', 'certifications'],
    dummyData: {
      contact: {
        name: 'SEBASTIAN BENNETT',
        jobTitle: 'Professional Accountant',
        email: 'hello@reallygreatsite.com',
        phone: '+123-456-7890',
        location: '123 Anywhere St., Any City',
      },
      summary:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.',
      education: [
        { degree: 'Senior Accountant', institution: 'Borcelle University', year: '2026-2030', gpa: '—' },
        { degree: 'Senior Accountant', institution: 'Borcelle University', year: '2023-2026', gpa: '—' },
      ],
      workExperience: [
        {
          position: 'Senior Accountant',
          company: 'Salford & Co.',
          duration: '2033-2035',
          description: 'Managed audits and financial reporting across multiple accounts.',
        },
        {
          position: 'Financial Accountant',
          company: 'Salford & Co.',
          duration: '2030-2033',
          description: 'Prepared statements and ensured compliance with standards.',
        },
      ],
      skills: ['Auditing', 'Financial Accounting', 'Financial Reporting', 'Budgeting', 'GAAP'],
      certifications: ['CPA', 'Chartered Accountant'],
    },
  },
  {
    id: 'classic-profile',
    name: 'Classic Profile',
    description: 'Single-column with prominent profile and clean dividers',
    layout: { type: 'single-column' },
    theme: {
      fontFamily: "'Georgia', 'Times New Roman', serif",
      nameSize: '28px',
      jobSize: '14px',
      bodySize: '11px',
      sectionSize: '12px',
      weightBold: 700,
      weightBody: 400,
      primary: '#111',
      secondary: '#333',
      accent: '#111',
      background: '#fff',
      divider: '#000',
      contactSeparator: ' | ',
      bullet: '•',
      sectionSpacing: '16px',
      itemSpacing: '10px',
      padding: '28px 36px',
    },
    sections: ['contact', 'summary', 'workExperience', 'education', 'certifications', 'skills'],
    dummyData: {
      contact: {
        name: 'CONNOR HAMILTON',
        jobTitle: 'Real Estate Agent',
        email: 'hello@reallygreatsite.com',
        phone: '123-456-7890',
        location: 'reallygreatsite.com',
      },
      summary:
        'Experienced agent with 5+ years helping clients find and negotiate their dream homes. Strong market analysis and communication skills.',
      workExperience: [
        {
          position: 'Real Estate Agent',
          company: 'Really Great Company',
          duration: 'Jun 2015 - Present',
          bullets: [
            'Negotiate contracts and complex real estate transactions',
            'Provide excellent customer service and maintain client files',
            'Develop marketing campaigns and host open houses',
          ],
        },
      ],
      education: [{ degree: 'B.A. Business Administration', institution: 'University', year: '2010 - 2014' }],
      certifications: ['Licensed Real Estate Agent', 'Certified Real Estate Negotiator', 'Top Sales Agent 2016'],
      skills: [
        'Market research',
        'Communication',
        'Negotiation',
        'Problem-solving',
        'Time management',
      ],
    },
  },
  {
    id: 'two-column-bold',
    name: 'Two-Column Bold',
    description: 'Two-column layout with bold headings and clear separation',
    layout: {
      type: 'two-column',
      columns: {
        left: ['contact', 'skills', 'certifications'],
        right: ['summary', 'workExperience', 'education'],
      },
    },
    theme: {
      fontFamily: "'Inter', Arial, sans-serif",
      nameSize: '30px',
      jobSize: '13px',
      bodySize: '11px',
      sectionSize: '13px',
      weightBold: 700,
      weightBody: 400,
      primary: '#0f172a',
      secondary: '#334155',
      accent: '#0f172a',
      background: '#ffffff',
      divider: '#0f172a',
      contactSeparator: ' • ',
      bullet: '•',
      sectionSpacing: '16px',
      itemSpacing: '10px',
      padding: '30px 34px',
    },
    sections: ['contact', 'summary', 'skills', 'workExperience', 'education', 'certifications'],
    dummyData: {
      contact: {
        name: 'ALEX MORGAN',
        jobTitle: 'Product Designer',
        email: 'alex.morgan@email.com',
        phone: '+1 555 222 1111',
        location: 'Remote',
      },
      summary:
        'Product designer focused on usable, accessible experiences. Partnered closely with PM and Eng to ship outcomes.',
      skills: ['UI Design', 'Figma', 'User Research', 'Prototyping', 'Design Systems', 'Accessibility'],
      workExperience: [
        {
          position: 'Senior Product Designer',
          company: 'Northwind Labs',
          duration: '2021 - Present',
          description: 'Led design for core platform, improved activation by 18%.',
        },
        {
          position: 'Product Designer',
          company: 'Contoso',
          duration: '2018 - 2021',
          description: 'Shipped mobile redesign increasing retention 12%.',
        },
      ],
      education: [{ degree: 'B.Des Interaction Design', institution: 'Art School', year: '2014 - 2018' }],
      certifications: ['NN/g UX Certification'],
    },
  },
  {
    id: 'elegant-serif',
    name: 'Elegant Serif',
    description: 'Single column, generous spacing, serif headings',
    layout: { type: 'single-column' },
    theme: {
      fontFamily: "'Merriweather', 'Times New Roman', serif",
      nameSize: '29px',
      jobSize: '14px',
      bodySize: '11px',
      sectionSize: '13px',
      weightBold: 700,
      weightBody: 400,
      primary: '#1f2937',
      secondary: '#4b5563',
      accent: '#111827',
      background: '#ffffff',
      divider: '#1f2937',
      contactSeparator: ' · ',
      bullet: '•',
      sectionSpacing: '20px',
      itemSpacing: '12px',
      padding: '34px 42px',
    },
    sections: ['contact', 'summary', 'workExperience', 'projects', 'education', 'skills'],
    dummyData: {
      contact: {
        name: 'PRIYA SHARMA',
        jobTitle: 'Data Analyst',
        email: 'priya.sharma@email.com',
        phone: '+91 98765 43210',
        location: 'Bangalore, IN',
      },
      summary:
        'Data analyst with experience turning business questions into dashboards and insights. Comfortable with SQL and Python.',
      workExperience: [
        {
          position: 'Data Analyst',
          company: 'InsightWorks',
          duration: '2020 - Present',
          description: 'Built reporting suite reducing manual ops by 30%.',
        },
      ],
      projects: [
        {
          name: 'Sales Forecasting',
          duration: 'Q2 2023',
          description: 'Created time-series forecasts improving accuracy by 8%.',
          technologies: ['Python', 'pandas'],
        },
      ],
      education: [{ degree: 'B.Tech Computer Science', institution: 'NIT', year: '2016 - 2020' }],
      skills: ['SQL', 'Python', 'Tableau', 'Statistics', 'A/B Testing'],
    },
  },
  {
    id: 'compact-ats',
    name: 'Compact ATS',
    description: 'ATS-friendly, tight spacing, clear headings',
    layout: { type: 'single-column' },
    theme: {
      fontFamily: "'Arial', sans-serif",
      nameSize: '26px',
      jobSize: '13px',
      bodySize: '10px',
      sectionSize: '12px',
      weightBold: 700,
      weightBody: 400,
      primary: '#111',
      secondary: '#222',
      accent: '#000',
      background: '#fff',
      divider: '#000',
      contactSeparator: ' | ',
      bullet: '•',
      sectionSpacing: '14px',
      itemSpacing: '8px',
      padding: '26px 32px',
    },
    sections: ['contact', 'summary', 'skills', 'workExperience', 'projects', 'education'],
    dummyData: {
      contact: {
        name: 'JORDAN LEE',
        jobTitle: 'Software Engineer',
        email: 'jordan.lee@email.com',
        phone: '+1 444 222 9999',
        location: 'Austin, TX',
      },
      summary:
        'Engineer focused on backend services and APIs with strong attention to reliability and performance.',
      skills: ['JavaScript', 'TypeScript', 'Node.js', 'REST', 'SQL', 'Docker'],
      workExperience: [
        {
          position: 'Backend Engineer',
          company: 'Acme Corp',
          duration: '2022 - Present',
          description: 'Own API layer and observability improvements.',
        },
      ],
      projects: [
        {
          name: 'Notifications Service',
          duration: '2023',
          description: 'Built scalable notifications system with retries and DLQ.',
          technologies: ['Node', 'RabbitMQ'],
        },
      ],
      education: [{ degree: 'B.S. Computer Science', institution: 'State University', year: '2017 - 2021' }],
    },
  },
]

export const DEFAULT_TEMPLATE_ID = TEMPLATES[0].id

